<?php

/**
 * Implementation of hook_cron().
 */
function drupalcamp_xhprof_cron() {
}

/**
 * Implemenatation of hook_user().
 */
function drupalcamp_xhprof_user($user) {
  if (user_access($user, 'access content'))
    return;
}

/**
 * Implementation of hook_menu().
 */
function drupalcamp_xhprof_menu() {
  $items['drupalcamp/test1'] = array(
    'title' => 'Sleep demo',
    'page callback' => 'drupalcamp_xhprof_sleep',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['drupalcamp/test2'] = array(
    'title' => 'HTTP Request demo',
    'page callback' => 'drupalcamp_xhprof_http_request',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['drupalcamp/test3'] = array(
    'title' => 'User list peak mem',
    'page callback' => 'drupalcamp_xhprof_users_list',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['drupalcamp/test4'] = array(
    'title' => 'taxonomy_get_children bug test',
    'page callback' => 'drupalcamp_xhprof_test4',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['drupalcamp/test5'] = array(
    'title' => 'xdebug test',
    'page callback' => 'drupalcamp_xhprof_xdebug',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of drupalcamp_xhprof_sleep().
 */
function drupalcamp_xhprof_sleep() {
  sleep(5);
  return t('Sleep test success');
}

function drupalcamp_xhprof_http_request() {
  drupal_http_request('http://profiling.drupalcamp.es/drupalcamp/test1');
  return t('HTTP request test success');
}

function drupalcamp_xhprof_users_list() {
  $users = db_query("SELECT uid FROM {users}");
  foreach ($users as $user) {
    $user = user_load($user->uid);
    if ($user->uid == 5)
      return t('Success');
  }
  return t('User list test success');
}

function drupalcamp_xhprof_test4() {
  $term = taxonomy_get_children(0);
  return t('taxonomy_get_children test success');
}

function drupalcamp_xhprof_xdebug() {
  $users = db_query("SELECT uid FROM {users}");
  foreach ($users as $user) {
    $user = user_load($user->uid);
    if ($user->uid == 5) {
      return t('User list test success');
    }
  }
}
